name: Test variables
on:
  push:

env:
  GO_VERSION: "1.22"
  USE_BROTLI: 1
  USE_LIBSODIUM: 1
  USE_LZO: 1

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        db: [ pg, mysql, sqlserver, redis, mongo, fdb, gp ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install deps
        run: sudo apt-get install liblzo2-dev brotli libsodium-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Make deps
        run: make deps

      - name: Build WAL-G
        run: make ${{ matrix.db }}_build

      - name: Test variables
        run: |
         main/${{ matrix.db }}/wal-g flags --config null.json

